### PR TITLE
FerriteCon 23

### PR DESCRIPTION
**Pull request by koehlerson**

### CODE REVIEW

**Comment by fredrikekre** [comment]
Perhaps it would be nice to keep the old page in a subdirectory?

**Comment by koehlerson** [comment]
Do you mean like this or do you want `archive/ferritecon22/` like structure?

**Comment by koehlerson** [comment]
Another question, should I then remove all the files from last year in the current "normal" folder?

**Comment by KnutAM** [comment]
Perhaps https://franklinjl.org/workflow/deploy/index.html#previewing_pull_requests can be used to make the old version available via a link on the new page? At least as a temporary solution, we could branch out e.g. a FerriteCon2022 branch, and then link to that "preview"? (At least as a temporary solution in case that is easier/faster?)

**Comment by koehlerson** [comment]
> Perhaps https://franklinjl.org/workflow/deploy/index.html#previewing_pull_requests can be used to make the old version available via a link on the new page? At least as a temporary solution, we could branch out e.g. a FerriteCon2022 branch, and then link to that "preview"? (At least as a temporary solution in case that is easier/faster?)

Is that related to this PR or a different PR/issue? I'm a bit confused :D

**Comment by KnutAM** [comment]
I meant that in case it is difficult to archive and get the right links working with Franklin, a quick-fix might be to use the suggested procedure to generate a "PR preview" as a way to conserve the old page (including all the CSS stuff) to avoid having to fiddle with that now.) I'm guessing a more long-term solution could be to set up the CI to include old versions from branches specific to each year or something. But if it works to just copy all the contents in a subfolder on the gh-pages branch without that being overwritten, that is easier!

**Comment by koehlerson** [comment]
I'm still missing the link between the PR preview and the issue. I moved now everything to the folder `2022` as @fredrikekre  suggested and if you build it, you can access it with `localhost:8000/2022`

Only problem is that if I override the `page_foot.html` all previous years have the most current `page_foot`

**Comment by KnutAM** [comment]
Looks like we had the deadline September 1st, so about a month before, but we also didn't publish the full details of the program beforehand (ref https://github.com/Ferrite-FEM/FerriteCon/commit/167d37f1700326fbebe345c1752092cde8c4d74d), and then we had no problems. 
For me the end of July is fine, but I guess the Swedes are on vacation in July and might prefer a bit later. Perhaps put it then and extend as usual :)

**Pull request merged**
